### ISSUE TITLE
MD restart with duplicated frames

### ISSUE THREAD

**Issue by BowenD-UCB** [rosswhitfield/ase#12]
Hi, I'm trying to continue/restart my MD in ASE. 
The problem is, after I pass the trajectory (in str) to the MD object, I have found that the last frame of the previous traje gets calculated again and appended into the new MD trajectory. Which basically means if I use the built-in append trajectory method, I will get two duplicated frames
And the MD object does not take in a sliced trajectory since that wil be of TrajectoryReader class that is not writable.

Is there any work around to continue a MD from a trajectory?

**Comment by arosen93** [comment]
@BowenD-UCB: This is not the main ASE repo. This is @rosswhitfield's fork. You need to open the issue here: https://gitlab.com/ase/ase.
