### ISSUE TITLE
Does ASE support relaxed PES scan in a molecule?

### ISSUE THREAD

**Issue by yangyinuo823** [rosswhitfield/ase#13]
I found some "Constraint" functions that can be used in optimization, but didn't find a function corresponding a relaxed PES scan process, such as a bond distance scan. Does anyone have any idea on this?

**Comment by arosen93** [comment]
This is not the official ASE repo. Refer to https://gitlab.com/ase/ase

**Comment by yangyinuo823** [comment]
Thank you!
