### ISSUE TITLE
Cannot import Filters

### ISSUE THREAD

**Issue by marcodigennaro** [rosswhitfield/ase#15]
I am following the example [here](https://wiki.fysik.dtu.dk/ase/ase/filters.html) but cannot import Filters:

![image](https://github.com/rosswhitfield/ase/assets/21054239/c983215c-ecc5-4ca6-95d1-b60fd2aecb8b)
 
Any idea?
Thanks

**Comment by Andrew-S-Rosen** [comment]
@marcodigennaro: This is not the official ASE repo. Please see https://gitlab.com/ase/ase

**Comment by marcodigennaro** [comment]
Hi, thanks a lot. I could download the '3.23.0b1' version from gitlab and install it.
Now trying to make the filters work. Cheers!
