### ISSUE TITLE
read_aims_output() returns pbc=False even though cell information is present

### ISSUE THREAD

**Issue by romankempt** [rosswhitfield/ase#6]
This specific function in aims.io returns pbc=False even though cell information is there. Stumbled across it accidentally when processing a lot of aims files.

https://github.com/rosswhitfield/ase/blob/c25bee34aef4750d66bfcec217f0f9e3a6ad51b5/ase/io/aims.py#L1648

[aims.txt](https://github.com/rosswhitfield/ase/files/9675898/aims.txt)

Steps to reproduce:
```python
from ase.io.aims import read_aims_output
atoms = read_aims_output("aims.out")
print(atoms)
... Atoms(symbols='Se2Pt', pbc=False, cell=[[3.72007051, -2.277e-05, 0.0], [-1.86001554, 3.22168695, 0.0], [0.0, 0.0, 149.99999984]], calculator=SinglePointCalculator(...))
```

**Comment by rosswhitfield** [comment]
This is just a mirror, please report at https://gitlab.com/ase/ase/-/issues
